### ISSUE TITLE
Column headings in elements.csv are incorrect

### ISSUE THREAD

**Issue by nanis** [mesbahamin/stoichiograph#2]
You have

```csv
Atomic_Number, Name, Symbol
1, H, Hydrogen
2, He, Helium
...
```
The headings should be `Atomic_Number, Symbol, Name`.

**Comment by nanis** [comment]
When one finds a file called `elements.csv` in the root of the repo, one assumes element symbols are read from this file ... It turns out the list is hardcoded in the module, and not read from `elements.csv`.

**Comment by mesbahamin** [comment]
Yes. That's a reasonable assumption. I forgot to get rid of this .csv, which I used in an early version of the project, and will remove it soon :)
