### ISSUE TITLE
Generating the groupings

### ISSUE THREAD

**Issue by Fuco1** [mesbahamin/stoichiograph#6]
Hey, just found your blog post about this project.  Nice writeup.

In the end you abandoned the idea of generating the groupings but I figured someone might get interested so I wrote up a little article on how to generate them with dynamic programming and I also included a proof which might interest some people getting into this (I get from your article the feeling it could be a good gateway drug to more formal computer science :))

Here's the article https://fuco1.github.io/2017-05-28-Generating-all-groupings-of-(1|2)*-summing-up-to-m.html

I don't care what you do just wanted to let you know.  Keep it up!

**Comment by mesbahamin** [comment]
Thanks for sharing this. I really enjoyed reading your article! I added a link to it in the "Further Reading" section of mine.

Please let me know on twitter if you add an RSS feed to your site :)

**Comment by Fuco1** [comment]
You're the second person today to ask about RSS.  I am researching the options and probably try to set it up tomorrow!
